<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>logo.ico</ApplicationIcon>
    <Version>2.0.0</Version>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
    <Title>QLauncher</Title>
    <Description>Современный кастомный лаунчер Minecraft в стиле Fluent Design</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="bg.png" />
    <None Remove="logo.ico" />
    <None Remove="logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Themes\DarkTheme.xaml" />
    <Page Remove="Themes\LightTheme.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CmlLib.Core.Auth.Microsoft" Version="3.3.1" />
    <PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
    <PackageReference Include="fNbt" Version="1.0.0" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    
  </ItemGroup>

  <ItemGroup>
    <Resource Include="bg.png" />
    <Resource Include="logo.ico" />
    <Resource Include="logo.png" />
    <Resource Include="Assets\theme_light.png" />
    <Resource Include="Assets\theme_dark.png" />
    <Resource Include="Assets\Loaders\vanilla.png" />
    <Resource Include="Assets\Loaders\fabric.png" />
    <Resource Include="Assets\Loaders\forge.png" />
    <Resource Include="Assets\Loaders\neoforge.png" />
    <Resource Include="Assets\Loaders\quilt.png" />
    <Resource Include="Themes\DarkTheme.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Resource>
    <Resource Include="Themes\LightTheme.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
